name: Build

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew app:assemble
      - uses: actions/upload-artifact@v3
        with:
          path: target
